"""empty message

Revision ID: 00452e7dd32b
Revises: 
Create Date: 2023-03-09 03:31:11.532496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00452e7dd32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('year', sa.Numeric(precision=4, scale=0), nullable=False),
    sa.Column('color', sa.String(length=150), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
